### PR TITLE
Fix another pre-release version bug

### LINKED ISSUE #17: VersionRange<^5.0.0-alpha> allowsAny VersionRange<^6.0.0-alpha>
Is that intentional?

### LINKED ISSUE #23: pub upgrade hangs
_From @zoechi on April 5, 2018 6:45_

This is the whole output and then it's stuck:

image

```yml
name: foo
version: 0.1.0
environment:
  sdk: '>=1.24.2 <2.0.0-f'

publish_to: none # prevent accidental publishing

dependencies:
  async: '^2.0.3'
  built_collection: ^3.0.0
  built_redux: 7.4.0-dev
  built_value: ^5.3.0
  http: ^0.11.3
  intl: ^0.15.0
  logging: ^0.11.3+1
  meta: ^1.1.1
  path: ^1.4.2
  rxdart: ^0.16.0

dev_dependencies:
  build: ^0.12.0
  build_runner: ^0.8.0
  built_value_generator: ^5.4.1
  built_value_test: ^5.3.0
  bwu_grinder_tasks: ^0.1.1-dev
  grinder: ^0.8.0
  source_gen: ^0.7.0
  test: ^0.12.20+3

dependency_overrides:
```

It works with `built_value_generator: ^5.3.0`

`Dart VM version: 2.0.0-dev.45.0 (Wed Apr 4 16:01:54 2018 +0200) on "macos_x64"`

_Copied from original issue: dart-lang/pub#1863_

### PR DESCRIPTION
**Pull request by nex3**
I think at this point we're testing this edge case in all our public
APIs.

Closes #17
Closes #23

### CODE REVIEW

File: lib/src/version_range.dart [hunk 1]
```diff
@@ -137,29 +137,26 @@ class VersionRange implements Comparable<VersionRange>, VersionConstraint {
...
-        intersectMax = other.max;
-        intersectIncludeMax = other.includeMax;
-      } else if (intersectMax == other.max && !other.includeMax) {
-        // The edges are the same, but one is exclusive, make it exclusive.
-        intersectIncludeMax = false;
+      Version intersectMax;
+      bool intersectIncludeMax;
+      if (allowsHigher(this, other)) {
+          intersectMax = other.max;
+          intersectIncludeMax = other.includeMax;
```
Comment (munificent) [inline lib/src/version_range.dart]: Too much indent.
